= Security Checklist
:reproducible:

This document contains a security checklist.

== General Security Principles

* Least privilege access
** Identities are only permitted to perform the most minimal set of functions necessary to fulfill a specific task
* Zero trust security
** Application components including microservices are considered discrete from each other and no component or microservice trusts any other
* Defense in depth
** Multiple layers of of security controls are implemented thoughout the system to provide redundancy in the event a security control fails or a vulnerability is exploited
* Identity foundation for both humans and machines
** TODO - ### description ###

== Account Management ( Cloud Privider)

TBD

== Identity Management (Cloud Platform)

* [ ] One IAM User/Identity per pyhisical person
* [ ] One IAM User/Identity per application
* [ ] One IAM Role per Application
* [ ] IAM credentials are not shared
* [ ] IAM credentials are not in code 
* [ ] ROOT account not used except for initial account setup
* [ ] ROOT IAM Credentials not used
*	[ ] Strong sign in mechanisms
** [ ] MFA (multi factor authentication) 
* [ ] Use temporary (short lived) credentials when appropriate
** Some examples of when this would be appropriate are:
*** Enterprise Identity Federation
***	Web identity federation
*** Cross account access
* [ ] Rotate credentials periodically
** [ ] For human identities, change passwords periodically 
** [ ] Use temporary credentials when possible instead of access keys
** [ ] For machine identities, use temporary credentials using IAM roles
* [ ] Store and use secrets securely

== Identity Management ( OpenShift)
* [ ] Configure an identity provider
* [ ] Create a cluster admin user
* [ ] Remove kubeadmin user (default OpenShift cluster admin user)
* [ ] One serviceaccount per application
* [ ] default service account is not used

== Permission Management (Cloud Platform)

Enforce least privelage access

* [ ] Identity base policies are specified - specify what the identity (user, group, role) can do
* [ ] Resource based policies – grants permission for a resource to a principal
* [ ] Permission boundary policies – set boundaries on maximum permission that can be set
* [ ] Organization Service Control Policies – defines max permissions at the account organization or organization unit

== Permission Management  (Open Shift)

* [ ] cluser-admin role is not used (except for the principle user who is actually the cluster admin)
** cluster-admin role in OpenShift can permission to perform all actions on all resources in the cluster
* [ ] Use Groups to aggregate users and apply RBAC policies
* [ ] Users have least privelage access
* [ ] ServiceAccounts have least privelage access

== Detection / Observability

* [ ] Detect unexpected and unwanted configuration changes at all levels of the application stack and delivery lifecycle
** Infrastructure
** Services
** Applications
** CI/CD
* [ ] Log account activity
* [ ] Log application activity
* [ ] Log CI/CD activity
* [ ] Analyze logs using a SIEM (security information and event management system)
* [ ] Implement actionable events – runbook or playbook with instructions on how to investigate and remediate the event
* [ ] Automate response to events



* [*] checked
** [ ] also checked
* [ ] not checked
* [ ] test test


Note:

Cloud Platforms are IBM Cloud, AWS, Azure, GCP
