apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
  namespace: tekton-chains-demo
spec:
  params:
    - name: url
      value: 'https://github.com/redhat-scholars/tekton-tutorial-greeter'
    - name: revision
      value: staging
  type: git
